In [1]:
import numpy as np

array = np.array([1, 2, 3, 4])
array = array*2

print(array)

print(type(array))

[2 4 6 8]
<class 'numpy.ndarray'>


In [2]:
array = np.array('A') 
print(array.ndim) # 0 dimensional array

0


In [3]:
array = np.array(['A', 'B', 'C']) 

print(array.ndim) # 1 dimensional array

1


In [4]:
array = np.array([['A', 'B', 'C'], 
                  ['D', 'E', 'F'], 
                  ['G', 'H', 'I']])

print(array.ndim) # 2 dimensional array

2


In [5]:
array = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']], 
                  [['j', 'k', 'l'], ['m', 'n', 'o'], ['p', 'q', 'r']],
                 [['s', 't', 'u'], ['v', 'x', 'y'], ['z', 'e', 'o']]])

print(array.ndim) # 3 dimensional array

print(array.shape)

print(array[0][0][0]) # chain indexing
print(array[0,1,2]) # multi dimensional indexing

word = array[0,0,0] + array[0,1,0] + array[0, 2, 2] + array[2,0,1] + array[2, 1, 2] + array[0,0,0]
print(word)


3
(3, 3, 3)
A
F
ADItyA


In [6]:
# slicing in numpy

array = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10,11,12], 
                  [13,14,15,16]])

# array[start:end:step]

print(array[0:4:2])

print(array[::-1]) # reverse order

print(array[:, 1]) # accessing coloumns

print(array[:, 0:3])
print(array[:, ::-1])

print(array[0:2, 2:4])

[[ 1  2  3  4]
 [ 9 10 11 12]]
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[ 2  6 10 14]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]
[[3 4]
 [7 8]]


In [7]:
# slicing in numpy

array = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10,11,12], 
                  [13,14,15,16]])

# array[start:end:step]

print(array[0:4:2])

print(array[::-1]) # reverse order

print(array[:, 1]) # accessing coloumns

print(array[:, 0:3])
print(array[:, ::-1])

print(array[0:2, 2:4])

[[ 1  2  3  4]
 [ 9 10 11 12]]
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[ 2  6 10 14]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]
[[3 4]
 [7 8]]


In [8]:
# vectorised math functions

array = np.array([1, 2., 3.])

print(np.sqrt(array))
print(np.round(array))
print(np.floor(array))
print(np.ceil(array))
print(np.pi)


radii = np.array([1, 2, 3])
print(np.pi * radii **2)

[1.         1.41421356 1.73205081]
[1. 2. 3.]
[1. 2. 3.]
[1. 2. 3.]
3.141592653589793
[ 3.14159265 12.56637061 28.27433388]


In [9]:
# element wise arithmetic

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [10]:
# comparison operatorrs

scores = np.array([91, 55, 100, 73, 82, 64])

print(scores == 100 )
print(scores >= 100 )

scores[scores < 60] = 0
print(scores)

[False False  True False False False]
[False False  True False False False]
[ 91   0 100  73  82  64]


In [11]:
# broadcasting allows numpy to perform operations on arrays with different shapes by 
# virtually expanding dimensions
# so they match the larger array's shape.

# the dimensions have the same size or one of the dimesions has the size of 1

array1 = np.array([[1, 2, 3, 4]])
array2 = np.array([[1], [2], [3], [4]])

print(array1.shape)
print(array2. shape)

print(array1 * array2)

(1, 4)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [12]:
array1 = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
array2 = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]])
print(array1.shape)
print(array2. shape)

print(array1*array2)

(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [13]:
# aggregate functions = summarize data and return a single value

array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(np.sum(array))
print(np.mean(array))
print(np.std(array))
print(np.var(array))
print(np.min(array))
print(np.max(array))
print(np.argmin(array))
print(np.argmax(array))

print(np.sum(array, axis= 1))

55
5.5
2.8722813232690143
8.25
1
10
0
9
[15 40]


In [19]:
# Filtering = Refers to the process of selecting elements from an array that match a given condition 
 
ages = np.array([[21, 23, 22, 53, 56, 12, 24, 52], 
                 [34, 23, 53, 25, 33, 25, 55, 33]])

teenagers = ages[ages < 18]
adult = ages[(ages >= 18) | (ages < 50)]
evens = ages[ages % 2 != 0]

print(evens)

print(teenagers)

adults = np.where(ages >=18, ages, 0)
print(adults)

[21 23 53 23 53 25 33 25 55 33]
[12]
[[21 23 22 53 56  0 24 52]
 [34 23 53 25 33 25 55 33]]


In [29]:
# random numbers

rng = np.random.default_rng(seed = 1)

print(rng.integers(low = 1, high = 101, size= (3,2)))

[[48 52]
 [76 96]
 [ 4 15]]


In [43]:
# floating point numbers
np.random.seed(seed = 1)
print(np.random.uniform(low = -1, high = 1, size =(3,3)))

[[-0.16595599  0.44064899 -0.99977125]
 [-0.39533485 -0.70648822 -0.81532281]
 [-0.62747958 -0.30887855 -0.20646505]]


In [46]:
# shuffle an array

rng = np.random.default_rng()
array = np.array([1, 2, 3, 4, 5])
rng.shuffle(array)
print(array)


[2 1 3 4 5]


In [54]:
rng = np.random.default_rng(seed = 4)

fruits = np.array(["apple", "orange", "banana", "coconut"])
fruits = rng.choice(fruits, size = 3)
print(fruits)

['banana' 'coconut' 'coconut']
